### ISSUE TITLE
Prepare for Release 1.6

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-core#431]
We want to get a v1.6 release out the door as soon as possible. Here's what I think is holding that up.

Please comment if you think anything else should be included or excluded.

## Required

- [x] Fix problem with ingester including `storage.driver` name in created product. (#423, #424)
- [x] Update release notes.

## Nice to have

- [ ] Fix for #420. Time extent being collapsed during ingest.

## Merge post release

- [x] #427 Changing the meaning of time based searches to line up with xarray/pandas
~~- [ ] #430  Caching of product extents in the index~~
- [ ] #484 Merging database extent and ranges with datacube-core

**Comment by omad** [comment]
Released!
